project 'msgApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'msgApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for msgApp
  pod 'Alamofire','4.7.3'
  pod 'SwiftyJSON','4.2.0'
  pod 'Socket.IO-Client-Swift'

end
